theme: jekyll-theme-minimal
title: "Kade Engine Legacy"
description: "Kade Engine Legacy is an engine for Friday Night Funkin' modding."
show_downloads: true
replace_index_with: "https://cors-thing.puyo.workers.dev/master/"
logo: "https://github.com/Goldie5fnf/Kade-Engine-Legacy/blob/main/assets/preload/images/KELLogo.png"
url: "https://Goldie5fnf.github.io/Kade-Engine-Legacy/"
